[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=E:\\software\\test1\\DB-QA-Agent-ty\\DB-QA-Agent-ty\\DB-QA-Agent-main\\setup\\DB-QA-Agent-Setup.exe
FriendlyName=DB-QA-Agent Setup
AppLaunched=installer_install.cmd
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[SourceFiles]
SourceFiles0=E:\\software\\test1\\DB-QA-Agent-ty\\DB-QA-Agent-ty\\DB-QA-Agent-main\\setup\\stage
[SourceFiles0]
%FILE0%=installer_install.cmd
%FILE1%=installer_install.ps1
%FILE2%=app.zip
[Strings]
FILE0=installer_install.cmd
FILE1=installer_install.ps1
FILE2=app.zip
